FROM ubuntu:latest

RUN apt-get update
RUN apt-get install -y g++ make cmake pkg-config
RUN apt-get install -y libhyperscan-dev libpcre3-dev libgtest-dev

WORKDIR /usr/src/gtest
RUN cmake CMakeLists.txt && make && make install

RUN apt-get install -y lldb

CMD /bin/bash
