version: '3'
services:
  devenv:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - "c:\\work\\logscan_project:/root/logscan_project"
      - "c:\\work\\logscan_testdata:/root/testdata"
    privileged: true

  prodenv:
    build: .
    image: logscan_cli:latest
    volumes:
      - "c:\\work\\logscan_testdata:/root/testdata"
